### ISSUE TITLE
No "calibrations" folder provided

### ISSUE THREAD

**Issue by aakash-saboo** [americofmoliveira/VesselSegmentation_ESWA#2]
I started to run the code for DRIVE dataset and it gave the error of not finding the "calibrations" folder. Please see the attached file for reference
![screenshot from 2019-01-12 20-02-20](https://user-images.githubusercontent.com/39874883/51071453-1a68c700-16a5-11e9-85f0-09eced7c9f8f.png)

**Comment by desti-nation** [comment]
Mee too. And what is calibrations of a dataset?

**Comment by americofmoliveira** [comment]
Hi,

Thank you for your interest in our research, and sorry for the delay in my response.

In fact, the calibration files were missing and we already added them. By abuse of language, we usually call _calibration_ to the _standardization_ process, that is, to the normalization of the data so that it acquires zero mean and unit variance.

 Let me know if you have any other problems :)
